pipeline{
    agent {label 'worker-node01'}

    stages{
        stage('Git Checkout'){
            steps{
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Anurag-Nagkirti/Jenkins.git'
            }
        }
    
        stage('Build and Compile'){
             steps{
                dir('04-python-jenkins-docker-app') {
                    sh 'echo "Building and compiling python code"'
                    sh 'python3 -m py_compile app.py'
                }

             }
         }

        stage('Test'){
              steps{
                dir('04-python-jenkins-docker-app') {
                    sh 'echo "Testing python code"'
                    sh 'python3 -m unittest discover tests'
                }
             }
        }

        stage('Run locally'){
            steps{
                dir('04-python-jenkins-docker-app') {
                    sh 'echo "running app locally"'
                    sh 'python3 app.py'
                }
            }
        }

        stage('Building Docker Image'){
            steps{
                dir('04-python-jenkins-docker-app') {
                    sh 'echo "building docker image"'
                    sh 'docker build -t anuragnagkirti/python-jenkins-docker-app:agent-testing .'
                }
            }
        }

        stage('Docker image pushing'){
            steps{
                dir('04-python-jenkins-docker-app') {
                    sh 'echo "pushing docker image to dockerhub"'
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'python3 app.py'
                }
            }
        }
    }
}
