pipeline{
    agent {label 'worker-node01'}

    stages{

        stage('Git checkout'){
            steps{
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Anurag-Nagkirti/Jenkins.git'
            }
        }

        stage('Build'){
            steps{
                dir('03-java-jenkins-docker-app') {
                    sh 'echo "cleaning pkg and building the code"'
                    sh 'mvn clean package'
                }

            }
        }

        stage('Test'){
            steps{
                dir('03-java-jenkins-docker-app') {
                    sh 'echo "Testing the code"'
                    sh 'mvn test'
                }
            }
        }

        stage('Docker image build'){
            steps{
                dir('03-java-jenkins-docker-app') {
                    sh 'echo "Building docker image"'
                    sh 'docker build -t anuragnagkirti/java-jenkin-docker-app:agent-testing .'
                }
            }
        }        

        stage('Docker run'){
            steps{
                dir('03-java-jenkins-docker-app') {
                    sh 'docker run --rm anuragnagkirti/java-jenkin-docker-app:agent-testing'
                }

            }
        }

        stage('Docker login and push image to Dockerhub'){
            steps{
                dir('03-java-jenkins-docker-app') {
                    withCredentials([usernamePassword(credentialsId: 'docker_credentials', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                      sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                      sh 'docker push anuragnagkirti/java-jenkin-docker-app:agent-testing'
                    }

                }

            }
        }
    }
}
