pipeline{
    agent any

    stages{

        stage('Git checkout'){
            steps{
                sh 'echo "Cloning code from github"'
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Anurag-Nagkirti/Jenkins.git'
            }
        }


        stage('Build'){
            steps{
                dir('04-python-jenkins-docker-app') {
                    sh 'echo "Building the code......"'
                    sh 'python3 -m py_compile app.py'
                }
            }
        }

        stage('Test'){
            steps{
                dir('04-python-jenkins-docker-app') {
                sh 'echo "Testing the code......"'
                sh 'python3 -m unittest discover tests'
                }
            }
        }

        stage('docker build image'){
            steps{
                dir('04-python-jenkins-docker-app') {
                sh 'echo "Building the docker image......"'
                sh 'docker build -t anuragnagkirti/python-jenkins-docker-app:v1 .'
                }
            }

        }

        stage('Docker run'){
            steps{
                dir('04-python-jenkins-docker-app') {
                sh 'echo "Running the application......"'
                sh 'docker run --rm anuragnagkirti/python-jenkins-docker-app:v1'
                }
            }
        }

        stage('Docker login and push'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'docker_cred', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                sh 'docker push anuragnagkirti/python-jenkins-docker-app:v1'    
                }

            }
        }
    }

    post{
        always{
            cleanWs()
        }

        success{
            sh 'echo "Job is successfully executed"'
        }

        failure{
            sh 'echo "Job is failed"'
        }
    }
}
